
harriotHuntTimes = {
    "Knudson": 50,
    "Clover Pass": 50,
    "Totem Byte": 40,
    "Lighthouse": 30,
    "Cambria": 45
}

whiteRiverTimes = {
    "Ward Cove": wardCoveTimes["White River"],
    "Dock 2": dock2Times["White River"],
    "Dock 1": dock1Times["White River"],
    "Dock 3": dock3Times["White River"],
    "Dock 4": dock4Times["White River"],
    "Lumberjack": lumberjackTimes["White River"],
    "George Inlet": georgeInletTimes["White River"],
    "Cannery": canneryTimes["White River"],
    "Rainforest": rainforestTimes["White River"],
    "Cape Fox Lodge": cfLodgeTimes["White River"],
    "Saxmon": saxmonTimes["White River"],
    "Disco": discoTimes["White River"],
    "Taquan": taquanTimes["White River"],
    "Jeep Base": jeepBaseTimes["White River"],
    "Harriot Hunt": harriotHuntTimes["White River"],
    "White River": 0,
    "Adventure Carts": 50,
    "Knudson": 60,
    "Clover Pass": 60,
    "Totem Byte": 50,
    "Lighthouse": 45,
    "Cambria": 50
}

adventureCartsTimes = {
    "Ward Cove": wardCoveTimes["Adventure Carts"],
    "Dock 2": dock2Times["Adventure Carts"],
    "Dock 1": dock1Times["Adventure Carts"],
    "Dock 3": dock3Times["Adventure Carts"],
    "Dock 4": dock4Times["Adventure Carts"],
    "Lumberjack": lumberjackTimes["Adventure Carts"],
    "George Inlet": georgeInletTimes["Adventure Carts"],
    "Cannery": canneryTimes["Adventure Carts"],
    "Rainforest": rainforestTimes["Adventure Carts"],
    "Cape Fox Lodge": cfLodgeTimes["Adventure Carts"],
    "Saxmon": saxmonTimes["Adventure Carts"],
    "Disco": discoTimes["Adventure Carts"],
    "Taquan": taquanTimes["Adventure Carts"],
    "Jeep Base": jeepBaseTimes["Adventure Carts"],
    "Harriot Hunt": harriotHuntTimes["Adventure Carts"],
    "White River": whiteRiverTimes["Adventure Carts"],
    "Adventure Carts": 0,
    "Knudson": 30,
    "Clover Pass": 40,
    "Totem Byte": 25,
    "Lighthouse": 5,
    "Cambria": 35
}

knudsonTimes = {
    "Ward Cove": wardCoveTimes["Knudson"],
    "Dock 2": dock2Times["Knudson"],
    "Dock 1": dock1Times["Knudson"],
    "Dock 3": dock3Times["Knudson"],
    "Dock 4": dock4Times["Knudson"],
    "Lumberjack": lumberjackTimes["Knudson"],
    "George Inlet": georgeInletTimes["Knudson"],
    "Cannery": canneryTimes["Knudson"],
    "Rainforest": rainforestTimes["Knudson"],
    "Cape Fox Lodge": cfLodgeTimes["Knudson"],
    "Saxmon": saxmonTimes["Knudson"],
    "Disco": discoTimes["Knudson"],
    "Taquan": taquanTimes["Knudson"],
    "Jeep Base": jeepBaseTimes["Knudson"],
    "Harriot Hunt": harriotHuntTimes["Knudson"],
    "White River": whiteRiverTimes["Knudson"],
    "Adventure Carts": adventureCartsTimes["Knudson"],
    "Knudson": 0,
    "Clover Pass": 10,
    "Totem Byte": 20,
    "Lighthouse": 30,
    "Cambria": 35
}

cloverPassTimes = {
    "Ward Cove": wardCoveTimes["Clover Pass"],
    "Dock 2": dock2Times["Clover Pass"],
    "Dock 1": dock1Times["Clover Pass"],
    "Dock 3": dock3Times["Clover Pass"],
    "Dock 4": dock4Times["Clover Pass"],
    "Lumberjack": lumberjackTimes["Clover Pass"],
    "George Inlet": georgeInletTimes["Clover Pass"],
    "Cannery": canneryTimes["Clover Pass"],
    "Rainforest": rainforestTimes["Clover Pass"],
    "Cape Fox Lodge": cfLodgeTimes["Clover Pass"],
    "Saxmon": saxmonTimes["Clover Pass"],
    "Disco": discoTimes["Clover Pass"],
    "Taquan": taquanTimes["Clover Pass"],
    "Jeep Base": jeepBaseTimes["Clover Pass"],
    "Harriot Hunt": harriotHuntTimes["Clover Pass"],
    "White River": whiteRiverTimes["Clover Pass"],
    "Adventure Carts": adventureCartsTimes["Clover Pass"],
    "Knudson": knudsonTimes["Clover Pass"],
    "Clover Pass": 0,
    "Totem Byte": 25,
    "Lighthouse": 30,
    "Cambria": 35,
}

totemByteTimes = {
    "Ward Cove": wardCoveTimes["Totem Byte"],
    "Dock 2": dock2Times["Totem Byte"],
    "Dock 1": dock1Times["Totem Byte"],
    "Dock 3": dock3Times["Totem Byte"],
    "Dock 4": dock4Times["Totem Byte"],
    "Lumberjack": lumberjackTimes["Totem Byte"],
    "George Inlet": georgeInletTimes["Totem Byte"],
    "Cannery": canneryTimes["Totem Byte"],
    "Rainforest": rainforestTimes["Totem Byte"],
    "Cape Fox Lodge": cfLodgeTimes["Totem Byte"],
    "Saxmon": saxmonTimes["Totem Byte"],
    "Disco": discoTimes["Totem Byte"],
    "Taquan": taquanTimes["Totem Byte"],
    "Jeep Base": jeepBaseTimes["Totem Byte"],
    "Harriot Hunt": harriotHuntTimes["Totem Byte"],
    "White River": whiteRiverTimes["Totem Byte"],
    "Adventure Carts": adventureCartsTimes["Totem Byte"],
    "Knudson": knudsonTimes["Totem Byte"],
    "Clover Pass": cloverPassTimes["Totem Byte"],
    "Totem Byte": 0,
    "Lighthouse": 20,
    "Cambria": 25
}

lightHouseTimes = {
    "Ward Cove": wardCoveTimes["Lighthouse"],
    "Dock 2": dock2Times["Lighthouse"],
    "Dock 1": dock1Times["Lighthouse"],
    "Dock 3": dock3Times["Lighthouse"],
    "Dock 4": dock4Times["Lighthouse"],
    "Lumberjack": lumberjackTimes["Lighthouse"],
    "George Inlet": georgeInletTimes["Lighthouse"],
    "Cannery": canneryTimes["Lighthouse"],
    "Rainforest": rainforestTimes["Lighthouse"],
    "Cape Fox Lodge": cfLodgeTimes["Lighthouse"],
    "Saxmon": saxmonTimes["Lighthouse"],
    "Disco": discoTimes["Lighthouse"],
    "Taquan": taquanTimes["Lighthouse"],
    "Jeep Base": jeepBaseTimes["Lighthouse"],
    "Harriot Hunt": harriotHuntTimes["Lighthouse"],
    "White River": whiteRiverTimes["Lighthouse"],
    "Adventure Carts": adventureCartsTimes["Lighthouse"],
    "Knudson": knudsonTimes["Lighthouse"],
    "Clover Pass": cloverPassTimes["Lighthouse"],
    "Totem Byte": totemByteTimes["Lighthouse"],
    "Lighthouse": 0,
    "Cambria": 15
}

cambriaTimes = {
    "Ward Cove": wardCoveTimes["Cambria"],
    "Dock 2": dock2Times["Cambria"],
    "Dock 1": dock1Times["Cambria"],
    "Dock 3": dock3Times["Cambria"],
    "Dock 4": dock4Times["Cambria"],
    "Lumberjack": lumberjackTimes["Cambria"],
    "George Inlet": georgeInletTimes["Cambria"],
    "Cannery": canneryTimes["Cambria"],
    "Rainforest": rainforestTimes["Cambria"],
    "Cape Fox Lodge": cfLodgeTimes["Cambria"],
    "Saxmon": saxmonTimes["Cambria"],
    "Disco": discoTimes["Cambria"],
    "Taquan": taquanTimes["Cambria"],
    "Jeep Base": jeepBaseTimes["Cambria"],
    "Harriot Hunt": harriotHuntTimes["Cambria"],
    "White River": whiteRiverTimes["Cambria"],
    "Adventure Carts": adventureCartsTimes["Cambria"],
    "Knudson": knudsonTimes["Cambria"],
    "Clover Pass": cloverPassTimes["Cambria"],
    "Totem Byte": totemByteTimes["Cambria"],
    "Lighthouse": lightHouseTimes["Cambria"],
    "Cambria": 0
}

TravelTimes = {
    "Ward Cove": wardCoveTimes,
    "Dock 2": dock2Times,
    "Dock 1": dock1Times,
    "Dock 3": dock3Times,
    "Dock 4": dock4Times,
    "Lumberjack": lumberjackTimes,
    "George Inlet": georgeInletTimes,
    "Cannery": canneryTimes,
    "Rainforest": rainforestTimes,
    "Cape Fox Lodge": cfLodgeTimes,
    "Saxmon": saxmonTimes,
    "Disco": discoTimes,
    "Taquan": taquanTimes,
    "Jeep Base": jeepBaseTimes,
    "Harriot Hunt": harriotHuntTimes,
    "White River": whiteRiverTimes,
    "Adventure Carts": adventureCartsTimes,
    "Knudson": knudsonTimes,
    "Clover Pass": cloverPassTimes,
    "Totem Byte": totemByteTimes,
    "Lighthouse": lightHouseTimes,
    "Cambria": cambriaTimes
}

